services:
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./_volumes/db/:/data/db
      - ./_volumes/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: medods_test
    ports:
      - 27017:27017
    
